{ config, lib, pkgs, inputs, ... }: {
  environment.systemPackages = with pkgs; [
    inputs.matugen.packages.${system}.default
    inputs.pond.packages.${system}.default
    inputs.zen-browser.packages.${system}.default
    ghostty
    wl-clipboard
    bluez
    pywalfox-native
    obs-studio
    lsd
    stow
    firefox
    cava
    youtube-music
    gh 
    nitch
    pipes
    niri
    brightnessctl
    font-manager
    fzf
    git
    grim
    slurp
    waybar
    starship
    oh-my-posh
    nautilus
    swww
    neovim
    vesktop
    rofi-wayland
    nwg-look
  ];
}
